// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260129110946_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("api.Data.Models.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<Guid>("AnonymousUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ANONYMOUS_USER_ID");

                    b.Property<DateTime>("ConnectedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("CONNECTED_AT_UTC");

                    b.Property<Guid>("RefApplication")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_APPLICATION");

                    b.HasKey("Id");

                    b.HasIndex("RefApplication");

                    b.ToTable("T_ACTIVITY", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<Guid>("RefOwner")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_OWNER");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.HasIndex("RefOwner");

                    b.ToTable("T_APPLICATION", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6932a69e-eaa0-4e9c-b4cf-d7a9c6524e4c"),
                            CreatedAt = new DateTime(2026, 1, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Application centrale",
                            IsActive = true,
                            Name = "Omnia",
                            RefOwner = new Guid("1c7850fa-2cf8-4716-9991-b26d4f169d21")
                        });
                });

            modelBuilder.Entity("api.Data.Models.ApplicationEncryptionKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("KeyEnc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("KEY_ENC");

                    b.Property<Guid>("RefApplication")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_APPLICATION");

                    b.HasKey("Id");

                    b.HasIndex("RefApplication")
                        .IsUnique()
                        .HasDatabaseName("UX_APPLICATION_ENCRYPTION_KEY_REF_APPLICATION");

                    b.ToTable("T_APPLICATION_ENCRYPTION_KEY", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.ApplicationMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<Guid>("RefApplication")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_APPLICATION");

                    b.Property<Guid>("RefRoleApplication")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_ROLE_APPLICATION");

                    b.Property<Guid>("RefUser")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_USER");

                    b.HasKey("Id");

                    b.HasIndex("RefRoleApplication");

                    b.HasIndex("RefUser");

                    b.HasIndex("RefApplication", "RefUser")
                        .IsUnique()
                        .HasDatabaseName("UX_APPLICATION_MEMBER_APP_USER");

                    b.ToTable("T_APPLICATION_MEMBER", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b"),
                            CreatedAt = new DateTime(2026, 1, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            RefApplication = new Guid("6932a69e-eaa0-4e9c-b4cf-d7a9c6524e4c"),
                            RefRoleApplication = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            RefUser = new Guid("1c7850fa-2cf8-4716-9991-b26d4f169d21")
                        });
                });

            modelBuilder.Entity("api.Data.Models.ApplicationSecret", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<Guid>("RefApplication")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_APPLICATION");

                    b.Property<string>("SecretEnc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SECRET_ENC");

                    b.Property<int>("Version")
                        .HasColumnType("int")
                        .HasColumnName("VERSION");

                    b.HasKey("Id");

                    b.HasIndex("RefApplication", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_APPLICATION_SECRET_REF_APPLICATION_VERSION");

                    b.ToTable("T_APPLICATION_SECRET", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1335d03-915b-48bb-9705-66070d0cc361"),
                            CreatedAt = new DateTime(2026, 1, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            RefApplication = new Guid("6932a69e-eaa0-4e9c-b4cf-d7a9c6524e4c"),
                            SecretEnc = "CfDJ8ApD0cbs3XhCviRx30E9Yehc-ljT-BV7IqeJrOqH-RMOzRbjJIVFzUjwlPBco3x7SN0XbRUYKPnRHNALG-iTWGke2lKD45HQ5VPjbgjugC9WOIfLhg0C7G4yN3JHpKojtt0w2LOo4ge8TaXJIVurrhWhzyXUqSu33DnC9Zf-LtIr",
                            Version = 1
                        });
                });

            modelBuilder.Entity("api.Data.Models.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Category")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("CATEGORY");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("FINGERPRINT");

                    b.Property<bool>("IsPatched")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IS_PATCHED");

                    b.Property<string>("Level")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("LEVEL");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Message");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("OCCURED_AT_UTC");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}")
                        .HasColumnName("PAYLOAD_JSON");

                    b.Property<Guid>("RefApplication")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_APPLICATION");

                    b.HasKey("Id");

                    b.HasIndex("RefApplication");

                    b.ToTable("T_ERROR_LOG", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.HmacNonce", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("EXPIRES_AT");

                    b.Property<string>("Nonce")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("NONCE");

                    b.Property<Guid>("RefApplication")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("REF_APPLICATION");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_HMAC_NONCE_EXPIRES_AT");

                    b.HasIndex("RefApplication", "Nonce")
                        .IsUnique()
                        .HasDatabaseName("UX_HMAC_NONCE_REF_APPLICATION_NONCE");

                    b.ToTable("T_HMAC_NONCE", (string)null);
                });

            modelBuilder.Entity("api.Data.Models.RoleApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ROLE_APPLICATION_NAME");

                    b.ToTable("T_ROLE_APPLICATION", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            Description = "Full access. Can manage members and delete the application.",
                            Name = "Owner"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e"),
                            Description = "Can edit the application and manage logs/activities.",
                            Name = "Maintainer"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a7b8-4c9d-0e1f-2a3b4c5d6e7f"),
                            Description = "Read-only access to the application, logs and activities.",
                            Name = "Viewer"
                        });
                });

            modelBuilder.Entity("api.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SALT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_USER_EMAIL");

                    b.ToTable("T_USER", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1c7850fa-2cf8-4716-9991-b26d4f169d21"),
                            Email = "MGxkV2lfdkupgorWnMHpeyIT9IX5GIDcQctl6JHkwo0=",
                            LastName = "7mKmhERhwYiFtwf2l6BJMQ==",
                            Name = "c8Tpx9kHQj0Xio6wAidnkg==",
                            Password = "wWwFqHINsN9P0TzRMd1d5yJQ9pz1nvw5ck0uRuVJu/D2kPPH/U/HylErGpB9g5RXA4mS8FqnAgdhXSuOgpabNQ==",
                            Salt = "vhLKoFuOfVK46NC4W056EkXEEsYAQogvnd/kOg4HU80="
                        });
                });

            modelBuilder.Entity("api.Data.Models.Activity", b =>
                {
                    b.HasOne("api.Data.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("RefApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("api.Data.Models.Application", b =>
                {
                    b.HasOne("api.Data.Models.User", "Owner")
                        .WithMany("OwnedApplications")
                        .HasForeignKey("RefOwner")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_APPLICATION_OWNER");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("api.Data.Models.ApplicationEncryptionKey", b =>
                {
                    b.HasOne("api.Data.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("RefApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_APPLICATION_ENCRYPTION_KEY_REF_APPLICATION");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("api.Data.Models.ApplicationMember", b =>
                {
                    b.HasOne("api.Data.Models.Application", "Application")
                        .WithMany("Members")
                        .HasForeignKey("RefApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_APPLICATION_MEMBER_APPLICATION");

                    b.HasOne("api.Data.Models.RoleApplication", "RoleApplication")
                        .WithMany("ApplicationMembers")
                        .HasForeignKey("RefRoleApplication")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_APPLICATION_MEMBER_ROLE");

                    b.HasOne("api.Data.Models.User", "User")
                        .WithMany("ApplicationMemberships")
                        .HasForeignKey("RefUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_APPLICATION_MEMBER_USER");

                    b.Navigation("Application");

                    b.Navigation("RoleApplication");

                    b.Navigation("User");
                });

            modelBuilder.Entity("api.Data.Models.ApplicationSecret", b =>
                {
                    b.HasOne("api.Data.Models.Application", "Application")
                        .WithMany("Secrets")
                        .HasForeignKey("RefApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_APPLICATION_SECRET_REF_APPLICATION");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("api.Data.Models.ErrorLog", b =>
                {
                    b.HasOne("api.Data.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("RefApplication")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("api.Data.Models.HmacNonce", b =>
                {
                    b.HasOne("api.Data.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("RefApplication")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("api.Data.Models.Application", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Secrets");
                });

            modelBuilder.Entity("api.Data.Models.RoleApplication", b =>
                {
                    b.Navigation("ApplicationMembers");
                });

            modelBuilder.Entity("api.Data.Models.User", b =>
                {
                    b.Navigation("ApplicationMemberships");

                    b.Navigation("OwnedApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
